# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e141b942f8940da5959a45b7ae998a703844e810093f79ee6dffbd82060aaa12148a1281228d127a79fde1edd78193fd76f71334d5fdcd001575da5c030bea9

test:
  secret_key_base: 4ed4033eb98cb9b4e7a4694fcce4772272c2bfca3154c9c03225b59edbde54248af813059e1367005bd834f34d13d14b55202ab641194a85a7903bcfb5630ebe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
